apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: diffchecker-ingress
  namespace: {{ .Values.namespace }}
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: diffchecker-service
                port:
                  number: {{ .Values.service.port }}
