image:
  repository: ghcr.io/rd-95/diffchecker
  tag: sha-c70b42db37b6a2c64bf0c7487fb8c1b4275e4424
  pullPolicy: Always

namespace: diffchecker

replicas: 2

service:
  type: ClusterIP
  port: 80
  targetPort: 5000

ingress:
  host: localhost

hpa:
  minReplicas: 2
  maxReplicas: 10
  cpuUtilization: 70

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "500m"
    memory: "256Mi"
